"""
Player Lookup

Provides a curated dictionary of active MLB players keyed by full name,
with their primary fantasy position and current MLB team.  Used to
power the autocomplete / autofill on the Roster page.

Data reflects 2026 active rosters.  Position represents the primary
fantasy-eligible slot (C, 1B, 2B, 3B, SS, OF, SP, RP, DH, UTIL).
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Player data: {display_name: {"position": str, "team": str}}
# ---------------------------------------------------------------------------

PLAYER_DATA: dict[str, dict[str, str]] = {
    # ── Catchers ──────────────────────────────────────────────────────────
    "William Contreras":    {"position": "C",  "team": "Milwaukee Brewers"},
    "Adley Rutschman":      {"position": "C",  "team": "Baltimore Orioles"},
    "J.T. Realmuto":        {"position": "C",  "team": "Philadelphia Phillies"},
    "Cal Raleigh":          {"position": "C",  "team": "Seattle Mariners"},
    "Sean Murphy":          {"position": "C",  "team": "Atlanta Braves"},
    "Gabriel Moreno":       {"position": "C",  "team": "Arizona Diamondbacks"},
    "Patrick Bailey":       {"position": "C",  "team": "San Francisco Giants"},
    "Salvador Perez":       {"position": "C",  "team": "Kansas City Royals"},
    "Jake Rogers":          {"position": "C",  "team": "Detroit Tigers"},
    "Kyle Higashioka":      {"position": "C",  "team": "San Diego Padres"},
    "Austin Wells":         {"position": "C",  "team": "New York Yankees"},
    "Tyler Stephenson":     {"position": "C",  "team": "Cincinnati Reds"},
    "Connor Wong":          {"position": "C",  "team": "Boston Red Sox"},
    "Jonah Heim":           {"position": "C",  "team": "Texas Rangers"},
    "Ryan Jeffers":         {"position": "C",  "team": "Minnesota Twins"},
    "Bo Naylor":            {"position": "C",  "team": "Cleveland Guardians"},
    "Logan O'Hoppe":        {"position": "C",  "team": "Los Angeles Angels"},
    "Christian Vazquez":    {"position": "C",  "team": "Minnesota Twins"},
    "Keibert Ruiz":         {"position": "C",  "team": "Washington Nationals"},
    "Elias Diaz":           {"position": "C",  "team": "Colorado Rockies"},
    "Francisco Alvarez":    {"position": "C",  "team": "New York Mets"},
    "Shea Langeliers":      {"position": "C",  "team": "Oakland Athletics"},

    # ── First Basemen ─────────────────────────────────────────────────────
    "Freddie Freeman":      {"position": "1B", "team": "Los Angeles Dodgers"},
    "Paul Goldschmidt":     {"position": "1B", "team": "New York Yankees"},
    "Pete Alonso":          {"position": "1B", "team": "New York Mets"},
    "Matt Olson":           {"position": "1B", "team": "Atlanta Braves"},
    "Vladimir Guerrero Jr.":{"position": "1B", "team": "Toronto Blue Jays"},
    "Christian Walker":     {"position": "1B", "team": "Arizona Diamondbacks"},
    "Josh Naylor":          {"position": "1B", "team": "Cleveland Guardians"},
    "Nathaniel Lowe":       {"position": "1B", "team": "Texas Rangers"},
    "Triston Casas":        {"position": "1B", "team": "Boston Red Sox"},
    "Spencer Torkelson":    {"position": "1B", "team": "Detroit Tigers"},
    "Ryan Mountcastle":     {"position": "1B", "team": "Baltimore Orioles"},
    "Vinnie Pasquantino":   {"position": "1B", "team": "Kansas City Royals"},
    "Carlos Santana":       {"position": "1B", "team": "Pittsburgh Pirates"},
    "Alec Bohm":            {"position": "1B", "team": "Philadelphia Phillies"},
    "Tyler Naquin":         {"position": "1B", "team": "Cincinnati Reds"},
    "Anthony Rizzo":        {"position": "1B", "team": "New York Yankees"},
    "Jose Abreu":           {"position": "1B", "team": "Houston Astros"},
    "Yuli Gurriel":         {"position": "1B", "team": "Miami Marlins"},
    "Justin Turner":        {"position": "1B", "team": "Toronto Blue Jays"},
    "C.J. Cron":            {"position": "1B", "team": "Colorado Rockies"},

    # ── Second Basemen ────────────────────────────────────────────────────
    "Jose Altuve":          {"position": "2B", "team": "Houston Astros"},
    "Marcus Semien":        {"position": "2B", "team": "Texas Rangers"},
    "Jeff McNeil":          {"position": "2B", "team": "New York Mets"},
    "Ozzie Albies":         {"position": "2B", "team": "Atlanta Braves"},
    "Gleyber Torres":       {"position": "2B", "team": "New York Yankees"},
    "Jazz Chisholm Jr.":    {"position": "2B", "team": "New York Yankees"},
    "Andrés Giménez":       {"position": "2B", "team": "Cleveland Guardians"},
    "Nico Hoerner":         {"position": "2B", "team": "Chicago Cubs"},
    "Luis Arraez":          {"position": "2B", "team": "San Diego Padres"},
    "Gavin Lux":            {"position": "2B", "team": "Los Angeles Dodgers"},
    "Whit Merrifield":      {"position": "2B", "team": "Philadelphia Phillies"},
    "DJ LeMahieu":          {"position": "2B", "team": "New York Yankees"},
    "Kolten Wong":          {"position": "2B", "team": "Seattle Mariners"},
    "Jonathan Schoop":      {"position": "2B", "team": "Detroit Tigers"},
    "Matt McLain":          {"position": "2B", "team": "Cincinnati Reds"},
    "Trea Turner":          {"position": "2B", "team": "Philadelphia Phillies"},

    # ── Third Basemen ─────────────────────────────────────────────────────
    "Jose Ramirez":         {"position": "3B", "team": "Cleveland Guardians"},
    "Austin Riley":         {"position": "3B", "team": "Atlanta Braves"},
    "Nolan Arenado":        {"position": "3B", "team": "St. Louis Cardinals"},
    "Manny Machado":        {"position": "3B", "team": "San Diego Padres"},
    "Alex Bregman":         {"position": "3B", "team": "Boston Red Sox"},
    "Gunnar Henderson":     {"position": "3B", "team": "Baltimore Orioles"},
    "Ryan McMahon":         {"position": "3B", "team": "Colorado Rockies"},
    "Jordan Walker":        {"position": "3B", "team": "St. Louis Cardinals"},
    "Brett Baty":           {"position": "3B", "team": "New York Mets"},
    "Jeimer Candelario":    {"position": "3B", "team": "Cincinnati Reds"},
    "Ke'Bryan Hayes":       {"position": "3B", "team": "Pittsburgh Pirates"},
    "Eugenio Suárez":       {"position": "3B", "team": "Arizona Diamondbacks"},
    "Yoan Moncada":         {"position": "3B", "team": "Chicago White Sox"},
    "Rafael Devers":        {"position": "3B", "team": "Boston Red Sox"},
    "Josh Jung":            {"position": "3B", "team": "Texas Rangers"},
    "Gio Urshela":          {"position": "3B", "team": "Minnesota Twins"},
    "Patrick Wisdom":       {"position": "3B", "team": "Chicago Cubs"},

    # ── Shortstops ────────────────────────────────────────────────────────
    "Bobby Witt Jr.":       {"position": "SS", "team": "Kansas City Royals"},
    "Corey Seager":         {"position": "SS", "team": "Texas Rangers"},
    "Francisco Lindor":     {"position": "SS", "team": "New York Mets"},
    "Wander Franco":        {"position": "SS", "team": "Tampa Bay Rays"},
    "Dansby Swanson":       {"position": "SS", "team": "Chicago Cubs"},
    "Oneil Cruz":           {"position": "SS", "team": "Pittsburgh Pirates"},
    "Carlos Correa":        {"position": "SS", "team": "Minnesota Twins"},
    "Bo Bichette":          {"position": "SS", "team": "Toronto Blue Jays"},
    "Xander Bogaerts":      {"position": "SS", "team": "San Diego Padres"},
    "CJ Abrams":            {"position": "SS", "team": "Washington Nationals"},
    "Ezequiel Tovar":       {"position": "SS", "team": "Colorado Rockies"},
    "Anthony Volpe":        {"position": "SS", "team": "New York Yankees"},
    "Geraldo Perdomo":      {"position": "SS", "team": "Arizona Diamondbacks"},
    "Ha-Seong Kim":         {"position": "SS", "team": "San Diego Padres"},
    "Elly De La Cruz":      {"position": "SS", "team": "Cincinnati Reds"},
    "JP Crawford":          {"position": "SS", "team": "Seattle Mariners"},
    "Orlando Arcia":        {"position": "SS", "team": "Atlanta Braves"},

    # ── Outfielders ───────────────────────────────────────────────────────
    "Aaron Judge":          {"position": "OF", "team": "New York Yankees"},
    "Ronald Acuña Jr.":     {"position": "OF", "team": "Atlanta Braves"},
    "Yordan Alvarez":       {"position": "OF", "team": "Houston Astros"},
    "Julio Rodríguez":      {"position": "OF", "team": "Seattle Mariners"},
    "Kyle Tucker":          {"position": "OF", "team": "Houston Astros"},
    "Mookie Betts":         {"position": "OF", "team": "Los Angeles Dodgers"},
    "Mike Trout":           {"position": "OF", "team": "Los Angeles Angels"},
    "Adolis García":        {"position": "OF", "team": "Texas Rangers"},
    "Corbin Carroll":       {"position": "OF", "team": "Arizona Diamondbacks"},
    "Jarren Duran":         {"position": "OF", "team": "Boston Red Sox"},
    "Teoscar Hernández":    {"position": "OF", "team": "Los Angeles Dodgers"},
    "Randy Arozarena":      {"position": "OF", "team": "Seattle Mariners"},
    "Lourdes Gurriel Jr.":  {"position": "OF", "team": "Arizona Diamondbacks"},
    "Michael Harris II":    {"position": "OF", "team": "Atlanta Braves"},
    "Bryan Reynolds":       {"position": "OF", "team": "Pittsburgh Pirates"},
    "Luis Robert Jr.":      {"position": "OF", "team": "Chicago White Sox"},
    "Cedric Mullins":       {"position": "OF", "team": "Baltimore Orioles"},
    "Seiya Suzuki":         {"position": "OF", "team": "Chicago Cubs"},
    "Ian Happ":             {"position": "OF", "team": "Chicago Cubs"},
    "Lane Thomas":          {"position": "OF", "team": "Washington Nationals"},
    "George Springer":      {"position": "OF", "team": "Toronto Blue Jays"},
    "Christian Yelich":     {"position": "OF", "team": "Milwaukee Brewers"},
    "Andrew McCutchen":     {"position": "OF", "team": "Pittsburgh Pirates"},
    "Trent Grisham":        {"position": "OF", "team": "New York Yankees"},
    "Cody Bellinger":       {"position": "OF", "team": "Chicago Cubs"},
    "Lars Nootbaar":        {"position": "OF", "team": "St. Louis Cardinals"},
    "Brandon Nimmo":        {"position": "OF", "team": "New York Mets"},
    "Mark Canha":           {"position": "OF", "team": "New York Mets"},
    "Alex Verdugo":         {"position": "OF", "team": "New York Yankees"},
    "Byron Buxton":         {"position": "OF", "team": "Minnesota Twins"},
    "Tyler O'Neill":        {"position": "OF", "team": "Boston Red Sox"},
    "Steven Kwan":          {"position": "OF", "team": "Cleveland Guardians"},
    "Josh Lowe":            {"position": "OF", "team": "Tampa Bay Rays"},
    "Jake Fraley":          {"position": "OF", "team": "Cincinnati Reds"},
    "Daulton Varsho":       {"position": "OF", "team": "Toronto Blue Jays"},
    "Oscar Gonzalez":       {"position": "OF", "team": "Cleveland Guardians"},
    "Trevor Larnach":       {"position": "OF", "team": "Minnesota Twins"},
    "Nick Castellanos":     {"position": "OF", "team": "Philadelphia Phillies"},
    "J.D. Martinez":        {"position": "OF", "team": "New York Mets"},
    "Giancarlo Stanton":    {"position": "OF", "team": "New York Yankees"},
    "Eloy Jiménez":         {"position": "OF", "team": "Chicago White Sox"},
    "Taylor Ward":          {"position": "OF", "team": "Los Angeles Angels"},
    "Hunter Renfroe":       {"position": "OF", "team": "Los Angeles Angels"},
    "Kerry Carpenter":      {"position": "OF", "team": "Detroit Tigers"},
    "Riley Greene":         {"position": "OF", "team": "Detroit Tigers"},
    "Jackson Chourio":      {"position": "OF", "team": "Milwaukee Brewers"},
    "Sal Frelick":          {"position": "OF", "team": "Milwaukee Brewers"},
    "Jesse Winker":         {"position": "OF", "team": "Washington Nationals"},
    "Willy Adames":         {"position": "OF", "team": "San Francisco Giants"},
    "Michael Conforto":     {"position": "OF", "team": "San Francisco Giants"},
    "Heliot Ramos":         {"position": "OF", "team": "San Francisco Giants"},
    "David Peralta":        {"position": "OF", "team": "Los Angeles Dodgers"},

    # ── Designated Hitters ────────────────────────────────────────────────
    "Shohei Ohtani":        {"position": "DH", "team": "Los Angeles Dodgers"},
    "Marcell Ozuna":        {"position": "DH", "team": "Atlanta Braves"},
    "Harold Ramírez":       {"position": "DH", "team": "Tampa Bay Rays"},
    "Jorge Soler":          {"position": "DH", "team": "San Francisco Giants"},
    "Joc Pederson":         {"position": "DH", "team": "Arizona Diamondbacks"},

    # ── Starting Pitchers ─────────────────────────────────────────────────
    "Zack Wheeler":         {"position": "SP", "team": "Philadelphia Phillies"},
    "Gerrit Cole":          {"position": "SP", "team": "New York Yankees"},
    "Spencer Strider":      {"position": "SP", "team": "Atlanta Braves"},
    "Dylan Cease":          {"position": "SP", "team": "San Diego Padres"},
    "Kevin Gausman":        {"position": "SP", "team": "Toronto Blue Jays"},
    "Logan Webb":           {"position": "SP", "team": "San Francisco Giants"},
    "Sandy Alcantara":      {"position": "SP", "team": "Miami Marlins"},
    "Framber Valdez":       {"position": "SP", "team": "Houston Astros"},
    "Corbin Burnes":        {"position": "SP", "team": "Baltimore Orioles"},
    "Shane Bieber":         {"position": "SP", "team": "Cleveland Guardians"},
    "Yoshinobu Yamamoto":   {"position": "SP", "team": "Los Angeles Dodgers"},
    "Tyler Glasnow":        {"position": "SP", "team": "Los Angeles Dodgers"},
    "Shota Imanaga":        {"position": "SP", "team": "Chicago Cubs"},
    "Freddy Peralta":       {"position": "SP", "team": "Milwaukee Brewers"},
    "Aaron Nola":           {"position": "SP", "team": "Philadelphia Phillies"},
    "Tarik Skubal":         {"position": "SP", "team": "Detroit Tigers"},
    "Tanner Bibee":         {"position": "SP", "team": "Cleveland Guardians"},
    "Brayan Bello":         {"position": "SP", "team": "Boston Red Sox"},
    "Hunter Brown":         {"position": "SP", "team": "Houston Astros"},
    "Ranger Suárez":        {"position": "SP", "team": "Philadelphia Phillies"},
    "Max Fried":            {"position": "SP", "team": "New York Yankees"},
    "Luis Castillo":        {"position": "SP", "team": "Seattle Mariners"},
    "George Kirby":         {"position": "SP", "team": "Seattle Mariners"},
    "Bryce Miller":         {"position": "SP", "team": "Seattle Mariners"},
    "Pablo López":          {"position": "SP", "team": "Minnesota Twins"},
    "Bailey Ober":          {"position": "SP", "team": "Minnesota Twins"},
    "MacKenzie Gore":       {"position": "SP", "team": "Washington Nationals"},
    "Patrick Corbin":       {"position": "SP", "team": "Washington Nationals"},
    "Edward Cabrera":       {"position": "SP", "team": "Miami Marlins"},
    "Braxton Garrett":      {"position": "SP", "team": "Miami Marlins"},
    "Miles Mikolas":        {"position": "SP", "team": "St. Louis Cardinals"},
    "Sonny Gray":           {"position": "SP", "team": "St. Louis Cardinals"},
    "Lance Lynn":           {"position": "SP", "team": "St. Louis Cardinals"},
    "Jordan Montgomery":    {"position": "SP", "team": "Arizona Diamondbacks"},
    "Merrill Kelly":        {"position": "SP", "team": "Arizona Diamondbacks"},
    "Zac Gallen":           {"position": "SP", "team": "Arizona Diamondbacks"},
    "Dane Dunning":         {"position": "SP", "team": "Texas Rangers"},
    "Nathan Eovaldi":       {"position": "SP", "team": "Texas Rangers"},
    "Andrew Heaney":        {"position": "SP", "team": "Texas Rangers"},
    "Martín Pérez":         {"position": "SP", "team": "Pittsburgh Pirates"},
    "Rich Hill":            {"position": "SP", "team": "Pittsburgh Pirates"},
    "José Berríos":         {"position": "SP", "team": "Toronto Blue Jays"},
    "Kevin Gausman":        {"position": "SP", "team": "Toronto Blue Jays"},
    "Chris Bassitt":        {"position": "SP", "team": "Toronto Blue Jays"},
    "Brandon Pfaadt":       {"position": "SP", "team": "Arizona Diamondbacks"},
    "Cristopher Sánchez":   {"position": "SP", "team": "Philadelphia Phillies"},
    "Nick Pivetta":         {"position": "SP", "team": "Boston Red Sox"},
    "Kutter Crawford":      {"position": "SP", "team": "Boston Red Sox"},
    "Luke Little":          {"position": "SP", "team": "Chicago Cubs"},
    "Justin Steele":        {"position": "SP", "team": "Chicago Cubs"},
    "Kyle Hendricks":       {"position": "SP", "team": "Chicago Cubs"},
    "Nestor Cortes":        {"position": "SP", "team": "New York Yankees"},
    "Carlos Rodón":         {"position": "SP", "team": "New York Yankees"},
    "Tylor Megill":         {"position": "SP", "team": "New York Mets"},
    "Kodai Senga":          {"position": "SP", "team": "New York Mets"},
    "Sean Manaea":          {"position": "SP", "team": "New York Mets"},
    "Mitch Keller":         {"position": "SP", "team": "Pittsburgh Pirates"},
    "Jared Jones":          {"position": "SP", "team": "Pittsburgh Pirates"},
    "Logan Gilbert":        {"position": "SP", "team": "Seattle Mariners"},
    "Robbie Ray":           {"position": "SP", "team": "San Francisco Giants"},
    "Blake Snell":          {"position": "SP", "team": "San Francisco Giants"},
    "Kyle Harrison":        {"position": "SP", "team": "San Francisco Giants"},
    "Taj Bradley":          {"position": "SP", "team": "Tampa Bay Rays"},
    "Shane McClanahan":     {"position": "SP", "team": "Tampa Bay Rays"},
    "Zach Eflin":           {"position": "SP", "team": "Tampa Bay Rays"},
    "Michael Wacha":        {"position": "SP", "team": "Kansas City Royals"},
    "Cole Ragans":          {"position": "SP", "team": "Kansas City Royals"},
    "Seth Lugo":            {"position": "SP", "team": "Kansas City Royals"},
    "Brady Singer":         {"position": "SP", "team": "Kansas City Royals"},
    "Garrett Crochet":      {"position": "SP", "team": "Boston Red Sox"},
    "Chris Sale":           {"position": "SP", "team": "Atlanta Braves"},
    "Reynaldo López":       {"position": "SP", "team": "Atlanta Braves"},
    "Joe Ryan":             {"position": "SP", "team": "Minnesota Twins"},
    "Hunter Greene":        {"position": "SP", "team": "Cincinnati Reds"},
    "Graham Ashcraft":      {"position": "SP", "team": "Cincinnati Reds"},
    "Nick Lodolo":          {"position": "SP", "team": "Cincinnati Reds"},
    "Reid Detmers":         {"position": "SP", "team": "Los Angeles Angels"},
    "Patrick Sandoval":     {"position": "SP", "team": "Los Angeles Angels"},
    "Ryan Feltner":         {"position": "SP", "team": "Colorado Rockies"},
    "Dinelson Lamet":       {"position": "SP", "team": "Colorado Rockies"},
    "Zack Greinke":         {"position": "SP", "team": "Kansas City Royals"},

    # ── Relief Pitchers ───────────────────────────────────────────────────
    "Emmanuel Clase":       {"position": "RP", "team": "Cleveland Guardians"},
    "Josh Hader":           {"position": "RP", "team": "Houston Astros"},
    "Edwin Díaz":           {"position": "RP", "team": "New York Mets"},
    "Ryan Helsley":         {"position": "RP", "team": "St. Louis Cardinals"},
    "Camilo Doval":         {"position": "RP", "team": "San Francisco Giants"},
    "Félix Bautista":       {"position": "RP", "team": "Baltimore Orioles"},
    "Jordan Romano":        {"position": "RP", "team": "Toronto Blue Jays"},
    "David Bednar":         {"position": "RP", "team": "Pittsburgh Pirates"},
    "Alexis Díaz":          {"position": "RP", "team": "Cincinnati Reds"},
    "Andrés Muñoz":         {"position": "RP", "team": "Seattle Mariners"},
    "Evan Phillips":        {"position": "RP", "team": "Los Angeles Dodgers"},
    "Daniel Hudson":        {"position": "RP", "team": "Los Angeles Dodgers"},
    "Craig Kimbrel":        {"position": "RP", "team": "Philadelphia Phillies"},
    "Robert Suarez":        {"position": "RP", "team": "San Diego Padres"},
    "Tanner Scott":         {"position": "RP", "team": "Los Angeles Dodgers"},
    "A.J. Minter":          {"position": "RP", "team": "Atlanta Braves"},
    "Paul Sewald":          {"position": "RP", "team": "Arizona Diamondbacks"},
    "Ryan Pressly":         {"position": "RP", "team": "Houston Astros"},
    "Kenley Jansen":        {"position": "RP", "team": "Boston Red Sox"},
    "Clay Holmes":          {"position": "RP", "team": "New York Yankees"},
    "Alex Lange":           {"position": "RP", "team": "Detroit Tigers"},
    "Mason Miller":         {"position": "RP", "team": "Oakland Athletics"},
    "Pete Fairbanks":       {"position": "RP", "team": "Tampa Bay Rays"},
    "Devin Williams":       {"position": "RP", "team": "New York Yankees"},
    "Will Smith":           {"position": "RP", "team": "Texas Rangers"},
    "Ian Kennedy":          {"position": "RP", "team": "Philadelphia Phillies"},
    "Taylor Rogers":        {"position": "RP", "team": "San Francisco Giants"},
    "Tyler Kinley":         {"position": "RP", "team": "Colorado Rockies"},
    "Carlos Estévez":       {"position": "RP", "team": "Los Angeles Angels"},
    "Aroldis Chapman":      {"position": "RP", "team": "Pittsburgh Pirates"},
    "Gregory Soto":         {"position": "RP", "team": "Philadelphia Phillies"},
    "Hunter Harvey":        {"position": "RP", "team": "Washington Nationals"},
    "Kyle Finnegan":        {"position": "RP", "team": "Washington Nationals"},
    "Jhoan Duran":          {"position": "RP", "team": "Minnesota Twins"},
    "Bryan Abreu":          {"position": "RP", "team": "Houston Astros"},
    "José Alvarado":        {"position": "RP", "team": "Philadelphia Phillies"},
    "Nick Anderson":        {"position": "RP", "team": "Atlanta Braves"},
    "Michael Kopech":       {"position": "RP", "team": "Los Angeles Dodgers"},
    "Trevor Megill":        {"position": "RP", "team": "Milwaukee Brewers"},
    "Hoby Milner":          {"position": "RP", "team": "Milwaukee Brewers"},
    "Devin Williams":       {"position": "RP", "team": "New York Yankees"},
    "Trevor Rosenthal":     {"position": "RP", "team": "Kansas City Royals"},
    "Jake Diekman":         {"position": "RP", "team": "Boston Red Sox"},
    "Liam Hendriks":        {"position": "RP", "team": "Boston Red Sox"},
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def get_player_names() -> list[str]:
    """Sorted list of all player display names."""
    return sorted(PLAYER_DATA.keys())


def get_player_info(name: str) -> dict[str, str] | None:
    """Return {"position": ..., "team": ...} for the given name, or None."""
    return PLAYER_DATA.get(name)
